### PR TITLE
New Datastax driver

### PR DESCRIPTION
**Pull request by ajs6f**
Upgrades to new major version of Datastax Cassandra driver.

https://github.com/trellis-ldp/trellis-cassandra/issues/62

### CODE REVIEW

**Comment by gregjan** [comment]
This was a chunk of work, pun intended! I'm eager to fire up the testbed for this. LGTM.

**Comment by ajs6f** [comment]
I hope to get it to you soon (hoped for yesterday, but hah!). I'm still nailing down the asynchrony in the binary side (RDF looks great now).

**Comment by acoburn** [comment]
One thing you might want to check is the awaitility tests -- earlier today I upgraded that version, and they removed the org.awaitility.Duration interface.

Take a look here for inspiration: https://github.com/trellis-ldp/trellis/commit/e93c68434a0d946abc302e86c23dd48bb73aa284#diff-5aee2e9621a2878ebbd9e99c2e58baa8R16

**Comment by ajs6f** [comment]
Thanks @acoburn -- I'm in the annoying situation where my local build is fine but Travis is angry. Hopefully I can find my way out soon.

**Comment by acoburn** [comment]
I'd try removing all the upstream jars in `~/.m2/repository/org/trellisldp`. If the local system still builds correctly, I'd go to the travis website, click on "More options" -> "Caches", and clear all the caches. That will often help.

**Comment by ajs6f** [comment]
Well, I'm getting timeout errors at Travis, not compilation problems, but why not update to the latest Trellis anyway?

**Comment by acoburn** [comment]
I'll hold off on merging https://github.com/trellis-ldp/trellis/pull/513 until you figure this out. That way I don't complicate matters, since it will require some more adjustments on the trellis-cassandra code (i.e. removal of the `ServiceBundler::getAgentService` method)

**Comment by ajs6f** [comment]
Ok, @acoburn and @gregjan (and any interested parties)-- I'm at my wits end. I get perfect builds every time locally, but Travis always fails by hanging at various points in various tests that have no obvious relationship to each other besides reading binary data. That tells me nothing because all of the changes for the new driver had to do with binary data. I'm guessing that there's some kind of race or deadlock, but: even better, Travis appears to be ignoring my log settings for the `integration-tests` module, which is preventing me from debugging. ARRRRGGG.

Can I get one of you to just check out this PR and do a local build, just to make me feel like I'm not insane? In particular, you should see a _huge_ amount of logging from that `integration-tests` module.

Thanks for any sanity checking!

**Comment by acoburn** [comment]
FWIW, a local build runs perfectly fine for me. I'll make a new branch and see what I can do w/r/t travis

**Comment by acoburn** [comment]
I got the travis build to succeed by increasing the memory configuration for maven -- in `.travis.yml` I added a line with `env: JAVA_OPTS="-Dmx2048"`. I'll push this change onto the branch here. If there are modifications (e.g. logging config) that you'd like to roll back

**Comment by ajs6f** [comment]
My word, thank you, @acoburn. I was flummoxed by that all afternoon! I am going to polish this PR up a bit (just removing or improving logging, that sort of thing). It's in an awful state that represents my increasing frustration this afternoon. I'll deal with it quickly and we can move on to better things.

**Comment by ajs6f** [comment]
Dang it, @acoburn, it just keeps getting odder. 

The Travis build for [the _branch_](https://github.com/trellis-ldp/trellis-cassandra/runs/226145309) failed (with no message, just hanging), while  the [_PR_ build](https://github.com/trellis-ldp/trellis-cassandra/runs/225928467) succeeded. I started [another branch](https://github.com/trellis-ldp/trellis-cassandra/tree/JustTravisFix) with just the commits through your adjustment to Travis' Maven memory  just to check and it showed the same behavior ([branch build failure](https://github.com/trellis-ldp/trellis-cassandra/runs/226145309), [PR build success](https://github.com/trellis-ldp/trellis-cassandra/runs/225928467)).

I'm actually starting to wonder if there is a pattern/clue here-- branch builds fail but the PR build itself succeeds. But why? And what would that mean?

Here's another weird thing. Locally, `LdpBinaryIT::testPatchBinaryDescription` now runs for me, which has been a thorn in my side for [almost a year](https://github.com/trellis-ldp/trellis/issues/301). But it fails on Travis. I don't know what that could possibly mean!

Oh, well, back to the tinkering.

**Comment by ajs6f** [comment]
Ok, I'm pretty well ready to give up on this. Travis errors out hanging on different tests (all of which seem to involve the new binary workflow) at what seem to be happenstance intervals. I do not see this behavior locally and neither has @acoburn. For reasons I cannot even guess at, Travis ignores any changes to logging settings, but only in one module (behavior it never showed before), so I have no logging and no way to debug.

@gregjan, do you want to try building this PR? If you build it without problems then I am half-inclined to merge it and just ignore Travis. I'm surprised to hear myself saying this, but CI has been a total waste of time for this project (`trellis-cassandra`). It has yet to produce one useful piece of information but it has wasted an enormous amount of time.

**Comment by ajs6f** [comment]
Okay, just for the record I've carefully confirmed that Travis is completely ignoring the `logback` configuration for the `integration-tests` module (in which the hangs are occurring). So I'm done. I have no idea how or why it could be doing that (the config is passed in a normal way via a system property in Maven config). I no longer care. I don't believe that Travis is giving useful information about this project.

**Comment by acoburn** [comment]
I agree. Travis is not adding value here. What if Travis is used more of a sanity check: verify that the code builds, passes any checkstyle rules and runs the basic unit tests. We can instruct Travis to skip the integration tests.

**Comment by acoburn** [comment]
I am inclined to merge this PR.

You may also want to add two adjustments to the travis configuration: 1) remove the java11 build, the cassandra machinery doesn't work well with this (esp. `nodetool`) 2) instruct the `script` stage to skip integration tests (`-DskipITs`)

**Comment by acoburn** [comment]
This is the modification the `.travis.yml` that I have been using: https://github.com/trellis-ldp/trellis-cassandra/commit/333d315dbfda598cc48b99fa51ef26182823fedd. Feel free to cherry-pick from that commit

**Comment by acoburn** [comment]
In terms of the possibility that something subtle is being missed, my suspicion would be that some resource isn't being closed. In some of the debug output, I noticed at one point that the requests seemed to hang on a second request of a resource. That may have been coincidental, but if I were to look anywhere, that's where I would start.

**Comment by ajs6f** [comment]
That is a very good tip. I will examine my impl of `Binary::getContent` very, very, closely.

**Comment by gregjan** [comment]
Just now catching up on the thread here and Travis excoriations. I
will build and test right now...

Okay, test timed out as follows:

Failed to execute goal
org.codehaus.mojo:cassandra-maven-plugin:3.6:start (start) on project
impl: Cassandra failed to start within 180s

I also see a memory warning from Maven:
[INFO] WARN  20:54:22 JMX settings in cassandra-env.sh have been
bypassed as the JMX connector server is already initialized. Please
refer to cassandra-env.(sh|ps1) for JMX configuration info
[INFO] WARN  20:54:22 Unable to lock JVM memory (ENOMEM). This can
result in part of the JVM being swapped out, especially with mmapped
I/O enabled. Increase RLIMIT_MEMLOCK or run Cassandra as root.
[INFO] WARN  20:54:22 jemalloc shared library could not be preloaded
to speed up memory allocations
[INFO] WARN  20:54:22 JMX is not enabled to receive remote
connections. Please see cassandra-env.sh for more info.
[INFO] ERROR 20:54:22 cassandra.jmx.local.port missing from
cassandra-env.sh, unable to start local JMX service.
[INFO] WARN  20:54:22 Use of com.sun.management.jmxremote.port at
startup is deprecated. Please use cassandra.jmx.remote.port instead.
[INFO] WARN  20:54:22 The JVM is not configured to stop on
OutOfMemoryError which can cause data corruption. Use one of the
following JVM options to configure the behavior on OutOfMemoryError:
-XX:+ExitOnOutOfMemoryError, -XX:+CrashOnOutOfMemoryError, or
-XX:OnOutOfMemoryError="<cmd args>;<cmd args>"
[INFO] WARN  20:54:22 Maximum number of memory map areas per process
(vm.max_map_count) 65530 is too low, recommended value: 1048575, you
can change it with sysctl.

**Comment by acoburn** [comment]
FYI I went ahead and merged trellis-ldp/trellis#513, so you'll need to modify any `ServiceBundler` implementation and/or use of the `AgentService`. Basically, the change will end up looking similar to this: https://github.com/trellis-ldp/trellis-ext-db/commit/b9153a96975be948cacdf350a844e352c70ada5d

**Comment by ajs6f** [comment]
Hi, @gregjan, that's (as the start of the error implies) something to do with the Mavven plugin used to run C* for tests. I haven't changed a thing about that for close to a year, from memory, certainly no changes in this PR. Can you try building again? It may have been a fluke, since I never saw that, Travis didn't show that, and (I think) @acoburn hasn't seen it.

**Comment by acoburn** [comment]
Nope, I've never seen that error. Just to be sure, you may want to run the tests with `clean`: `mvn clean verify`

**Comment by gregjan** [comment]
I'm trying to get the branch to "mvn verify" now. It should run against the latest trellis master build, yes?

**Comment by acoburn** [comment]
@gregjan I can add a commit to catch up with the Trellis API. I made a [similar change](https://github.com/trellis-ldp/trellis-cassandra/commit/0a5ffc3d462d95d6571b3fc741f7d45594d98983) on a different branch.

**Comment by gregjan** [comment]
thanks, testing again.

**Review by gregjan — APPROVED** [review]
I'm Greg Jansen and I approve this pull request.

**Comment by gregjan** [comment]
I succeeded in verifying my local branch.

**Comment by ajs6f** [comment]
Closing in favor of a number of smaller and more management PRs, starting with #76 .

**Pull request closed without merging**
