### PR TITLE
Memento

### PR DESCRIPTION
**Pull request by ajs6f**
Full Memento functionality.

### CODE REVIEW

**Comment by ajs6f** [comment]
Log got too long for Travis-CI, need to turn it down.

**Comment by ajs6f** [comment]
Now Travis-CI is failing because of [its very old version of Cassandra](https://github.com/travis-ci/travis-ci/issues/6420). I give up. Switching in another branch to some other CI, maybe Circle.

**Comment by acoburn** [comment]
Circle-CI is pretty nice. I had it running at one point with Trellis, and builds finished _minutes_ earlier than with Travis-CI. I did find it to be a little flaky at times, and that's why I stopped using it. I also just started using AWS (CodeCommit for the git repo, CodeBuild for the build & test, and CodePipeline for gluing it all together). The only downside with AWS is that it actually costs money: ~$0.01 per build-minute, which is (admittedly) not much

**Comment by ajs6f** [comment]
I need to check into our site budget for AWS-- it includes some things and not others, and I don't know whether it would include their CI. I'll take a look at Circle.

**Comment by acoburn** [comment]
I have an CircleCI org that is tied to the trellis-ldp github org: https://circleci.com/gh/trellis-ldp. I think that, in order to use that CircleCI org, we'd need to move this repo into the github trellis-ldp org (though I could be wrong).

**Comment by ajs6f** [comment]
Ok, cool-- see https://github.com/ajs6f/trellis-cassandra/issues/21 for that migration. Let's take any further conversation about CircleCI over there.

**Pull request merged**
