### PR TITLE
Some updates to align with upstream

### PR DESCRIPTION
**Pull request by acoburn**
This makes use of the `trellis-bom` artifact trellis-ldp/trellis#501
This adjusts the `Binary::getContent` method as per trellis-ldp/trellis#510
This also removes the `EtagGenerator` interface that was removed in trellis-ldp/trellis#497

### CODE REVIEW

**Comment by ajs6f** [comment]
Hey, @acoburn, thanks so much for this. I've got #73 finally landing (just some cleanup and adjusting logging left) so I'm going to finish that today and then pull this in. I might need to rebase it after #73 because that 'un is a chunk.

**Comment by ajs6f** [comment]
Hello @acoburn and @gatos-jd! I'm (partly) back and (slowly) picking up work. This PR is throwing:
```
ERROR] COMPILATION ERROR : 
[ERROR] /home/travis/build/trellis-ldp/trellis-cassandra/webapp/src/main/java/edu/si/trellis/CassandraServiceBundler.java:[22,5] annotation type not applicable to this kind of declaration
[ERROR] /home/travis/build/trellis-ldp/trellis-cassandra/webapp/src/main/java/edu/si/trellis/CassandraServiceBundler.java:[43,5] annotation type not applicable to this kind of declaration
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project webapp: Compilation failure: Compilation failure: 
[ERROR] /home/travis/build/trellis-ldp/trellis-cassandra/webapp/src/main/java/edu/si/trellis/CassandraServiceBundler.java:[22,5] annotation type not applicable to this kind of declaration
[ERROR] /home/travis/build/trellis-ldp/trellis-cassandra/webapp/src/main/java/edu/si/trellis/CassandraServiceBundler.java:[43,5] annotation type not applicable to this kind of declaration
[ERROR] -> [Help 1]
```
Is that related to the changes in `@NoopImplementation`?

**Comment by acoburn** [comment]
@ajs6f it seems that this error was due to caching outdated artifacts. After clearing the cache and restarting the build, everything appears much better.

**Comment by ajs6f** [comment]
@acoburn Right, good. I need to rebase #75 (and its descendants) onto this and I will merge it. Thank you!

**Pull request merged**
